In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/iris.csv")

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
x1 = df.iloc[:,1]
x2 = df.iloc[:,2]

### Calculating Covariance matrix

In [8]:
x1_mean = sum(x1) / len(x1)
x2_mean = sum(x2) / len(x2)

In [9]:
# cov(X,Y) = Sum of all((X -X_mean) * (Y - Y_mean) / (N -1))

cov_x1x2 = 0
cov_x1x1 = 0
cov_x2x2 = 0

n = len(x1)

for x1_i, x2_i in zip(x1,x2):
    cov_x1x2 += ((x1_i - x1_mean) * (x2_i - x2_mean))
    cov_x1x1 += ((x1_i - x1_mean) * (x1_i - x1_mean))
    cov_x2x2 += ((x2_i - x2_mean) * (x2_i - x2_mean))

cov_x1x2 = cov_x1x2 / (n-1)
cov_x1x1 = cov_x1x1 / (n-1)
cov_x2x2 = cov_x2x2 / (n-1)

print(cov_x1x2, cov_x1x1, cov_x2x2)

-0.03926845637583892 0.6856935123042505 0.18800402684563763


In [12]:
C = [[cov_x1x1, cov_x1x2], [cov_x1x2, cov_x2x2]]
print("Covariance matrix : ")
C

Covariance matrix : 


[[0.6856935123042505, -0.03926845637583892],
 [-0.03926845637583892, 0.18800402684563763]]

### Compute Eigen values and Eigen vectors

In [13]:
values, vectors = np.linalg.eig(C)

In [14]:
print("Eigen values :")
values

Eigen values :


array([0.6887728 , 0.18492474])

In [15]:
print("Eigen vectors :")
vectors

Eigen vectors :


array([[ 0.99693955,  0.07817635],
       [-0.07817635,  0.99693955]])

### Finding first principal component

In [16]:
eigen_val = max(values)
val_index = list(values).index(eigen_val)
eigen_vect = vectors[:, val_index]

print("Eigen vector corresponsding to first p.c :")
eigen_vect

Eigen vector corresponsding to first p.c :


array([ 0.99693955, -0.07817635])

### Transforming original dataset along principal component

In [18]:
new_x = [(x1[i] * eigen_vect[0]) + (x2[i] * eigen_vect[1]) for i in range(n)] 
new_df = pd.DataFrame(new_x)

In [19]:
new_df.head()

0
0  4.810774
1  4.650475
2  4.435452
3  4.343575
4  4.703263